# Generated by Django 3.2.5 on 2022-02-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
