# Generated by Django 3.2.5 on 2022-02-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_auto_20220228_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
