# Generated by Django 3.2.5 on 2022-02-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_administrator_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='administrator',
            name='last_name',
            field=models.CharField(default=True, max_length=15),
            preserve_default=False,
        ),
    ]
