# Generated by Django 3.2.5 on 2022-03-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_auto_20220228_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='company',
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
