# Generated by Django 4.1.5 on 2023-09-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_alter_project_end_time_alter_project_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='company',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='price',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.AddField(
            model_name='project',
            name='phone',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
