# Generated by Django 4.1.5 on 2023-09-27 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_rename_client_project_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='company_name',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='contact_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='email',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='phone',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.administrator')),
            ],
        ),
    ]
